language: ruby
rvm:
  - 1.9.3
before_script:
  - mysql -e 'create database bcmets_test;'
script:
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rspec spec
  - bundle exec cucumber features
