language: ruby
rvm:
  - 2.1.1
before_script:
  - mysql -e 'create database bcmets_test;'
script:
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rspec spec
  - bundle exec cucumber features
