# SQLite version 3.x
development:
  adapter: mysql
  database: bcmets_development
  user: pete
  socket: /tmp/mysql.sock

test: &TEST
  adapter: mysql
  database: bcmets_test
  user: pete
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: bcmets_rails
  user: pete
  socket: /var/lib/mysql/mysql.sock

cucumber:
  <<: *TEST
