# SQLite version 3.x
development:
  adapter: mysql2
  database: bcmets_development
  user: pete
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: bcmets_test
  user: pete
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  database: bcmets_rails
  user: pete
  socket: /var/lib/mysql/mysql.sock

cucumber:
  adapter: mysql2
  database: bcmets_test
  user: pete
  socket: /tmp/mysql.sock
