# SQLite version 3.x
development:
  adapter: mysql2
  database: bcmets
  user: root

test:
  adapter: mysql2
  database: bcmets_test
  user: root

production:
  adapter: mysql2
  database: bcmets_rails
  user: pete
  socket: /var/lib/mysql/mysql.sock
