#!/usr/bin/env ruby

ENV['RAILS_ENV'] = ARGV.first || ENV['RAILS_ENV'] || 'development'

require File.dirname(__FILE__) + '/../config/boot'
require "#{RAILS_ROOT}/config/environment"


def each_message(mbox_filename)
  starting = true
  article = ''
  File.open(mbox_filename) do |file|
    file.each_line do |line|
      if line =~ /^From (.*)/
        if !starting
          yield article
          article = ''
        end
        starting = false
      end
      article += line
    end
  end
  yield article unless starting
end

if ARGV.blank?
  puts "Usage: #{$0} file..."
  exit
end

ARGV.shift
for file in ARGV
  each_message(file) do |message|
    article = Article.parse(message)
    article.save
  end
end
Article.link_threads
